//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MemoryCleaner.Langs.Pages.MainPage {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MainPage_I18n {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainPage_I18n() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MemoryCleaner.Langs.Pages.MainPage.MainPage_I18n", typeof(MainPage_I18n).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   重写当前线程的 CurrentUICulture 属性，对
        ///   使用此强类型资源类的所有资源查找执行重写。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 AutoMinimizedAndStart 的本地化字符串。
        /// </summary>
        public static string AutoMinimizedAndStart {
            get {
                return ResourceManager.GetString("AutoMinimizedAndStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EmptyModifiedPageList 的本地化字符串。
        /// </summary>
        public static string EmptyModifiedPageList {
            get {
                return ResourceManager.GetString("EmptyModifiedPageList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EmptyModifiedPageListTip 的本地化字符串。
        /// </summary>
        public static string EmptyModifiedPageListTip {
            get {
                return ResourceManager.GetString("EmptyModifiedPageListTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EmptyPrioity0StandbyList 的本地化字符串。
        /// </summary>
        public static string EmptyPrioity0StandbyList {
            get {
                return ResourceManager.GetString("EmptyPrioity0StandbyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EmptyPrioity0StandbyListTip 的本地化字符串。
        /// </summary>
        public static string EmptyPrioity0StandbyListTip {
            get {
                return ResourceManager.GetString("EmptyPrioity0StandbyListTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EmptyStandbyList 的本地化字符串。
        /// </summary>
        public static string EmptyStandbyList {
            get {
                return ResourceManager.GetString("EmptyStandbyList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EmptyStandbyListTip 的本地化字符串。
        /// </summary>
        public static string EmptyStandbyListTip {
            get {
                return ResourceManager.GetString("EmptyStandbyListTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EmptySystemWorkingSets 的本地化字符串。
        /// </summary>
        public static string EmptySystemWorkingSets {
            get {
                return ResourceManager.GetString("EmptySystemWorkingSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EmptySystemWorkingSetsTip 的本地化字符串。
        /// </summary>
        public static string EmptySystemWorkingSetsTip {
            get {
                return ResourceManager.GetString("EmptySystemWorkingSetsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EmptyWorkingSets 的本地化字符串。
        /// </summary>
        public static string EmptyWorkingSets {
            get {
                return ResourceManager.GetString("EmptyWorkingSets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 EmptyWorkingSetsTip 的本地化字符串。
        /// </summary>
        public static string EmptyWorkingSetsTip {
            get {
                return ResourceManager.GetString("EmptyWorkingSetsTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ExecuteNow 的本地化字符串。
        /// </summary>
        public static string ExecuteNow {
            get {
                return ResourceManager.GetString("ExecuteNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 FreeMemory 的本地化字符串。
        /// </summary>
        public static string FreeMemory {
            get {
                return ResourceManager.GetString("FreeMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 LanuchOnUserLogon 的本地化字符串。
        /// </summary>
        public static string LanuchOnUserLogon {
            get {
                return ResourceManager.GetString("LanuchOnUserLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 MemoryMetrics 的本地化字符串。
        /// </summary>
        public static string MemoryMetrics {
            get {
                return ResourceManager.GetString("MemoryMetrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ModeSwitch 的本地化字符串。
        /// </summary>
        public static string ModeSwitch {
            get {
                return ResourceManager.GetString("ModeSwitch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NoCurrentTasks 的本地化字符串。
        /// </summary>
        public static string NoCurrentTasks {
            get {
                return ResourceManager.GetString("NoCurrentTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ProgramTasks 的本地化字符串。
        /// </summary>
        public static string ProgramTasks {
            get {
                return ResourceManager.GetString("ProgramTasks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 RammapMode 的本地化字符串。
        /// </summary>
        public static string RammapMode {
            get {
                return ResourceManager.GetString("RammapMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ResidualMode 的本地化字符串。
        /// </summary>
        public static string ResidualMode {
            get {
                return ResourceManager.GetString("ResidualMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Start 的本地化字符串。
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Stop 的本地化字符串。
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TimeMode 的本地化字符串。
        /// </summary>
        public static string TimeMode {
            get {
                return ResourceManager.GetString("TimeMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 TotalSystemMemory 的本地化字符串。
        /// </summary>
        public static string TotalSystemMemory {
            get {
                return ResourceManager.GetString("TotalSystemMemory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UsedMemory 的本地化字符串。
        /// </summary>
        public static string UsedMemory {
            get {
                return ResourceManager.GetString("UsedMemory", resourceCulture);
            }
        }
    }
}
